/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

import java.awt.Dimension;

/**
 *
 * @author Alejandro
 */
public class VistaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form VistaPrincipal
     * @param d
     */
    public VistaPrincipal(Dimension d){
        this.setSize(d);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMenuMonitor = new javax.swing.JMenu();
        GestionMonitor = new javax.swing.JMenuItem();
        jMenuSocio = new javax.swing.JMenu();
        GestionSocio = new javax.swing.JMenuItem();
        jMenuItemCuota = new javax.swing.JMenuItem();
        jMenuActividad = new javax.swing.JMenu();
        SociosPorActividad = new javax.swing.JMenuItem();
        jMenuSalir = new javax.swing.JMenu();
        SalirApliciación = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Body Perfect");

        jMenuMonitor.setText("Monitores");

        GestionMonitor.setText("Gestión de Monitores");
        GestionMonitor.setActionCommand("GestionMonitores");
        jMenuMonitor.add(GestionMonitor);

        jMenuBar1.add(jMenuMonitor);

        jMenuSocio.setText("Socio");

        GestionSocio.setText("Gestión de Socios");
        GestionSocio.setActionCommand("GestionSocios");
        jMenuSocio.add(GestionSocio);

        jMenuItemCuota.setText("Cuota de Socio");
        jMenuItemCuota.setActionCommand("CuotadeSocio");
        jMenuSocio.add(jMenuItemCuota);

        jMenuBar1.add(jMenuSocio);

        jMenuActividad.setText("Actividad");

        SociosPorActividad.setText("Socios por Actividad");
        SociosPorActividad.setActionCommand("SociosporActividad");
        jMenuActividad.add(SociosPorActividad);

        jMenuBar1.add(jMenuActividad);

        jMenuSalir.setText("Salir");

        SalirApliciación.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_ESCAPE, 0));
        SalirApliciación.setText("Salir Aplicación");
        SalirApliciación.setActionCommand("SalirAplicacion");
        SalirApliciación.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SalirApliciaciónActionPerformed(evt);
            }
        });
        jMenuSalir.add(SalirApliciación);

        jMenuBar1.add(jMenuSalir);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 277, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SalirApliciaciónActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SalirApliciaciónActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SalirApliciaciónActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JMenuItem GestionMonitor;
    public javax.swing.JMenuItem GestionSocio;
    public javax.swing.JMenuItem SalirApliciación;
    public javax.swing.JMenuItem SociosPorActividad;
    private javax.swing.JMenu jMenuActividad;
    private javax.swing.JMenuBar jMenuBar1;
    public javax.swing.JMenuItem jMenuItemCuota;
    private javax.swing.JMenu jMenuMonitor;
    private javax.swing.JMenu jMenuSalir;
    private javax.swing.JMenu jMenuSocio;
    // End of variables declaration//GEN-END:variables
}
